name: "units-test"
on:
  push:
    branches: [master]
  #pull_request:
  #push:
  #  branches:
  #    - master
  #    - 'releases/*'

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: npm ci
    - run: npm test

  # test action works running from the graph  
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./
      with:
        service_account: 'Service Account Value'
        project_name: 'Project Name Value'
